general:
  focus_follows_cursor: false
  cursor_follows_focus: false
  toggle_workspace_on_refocus: false
  show_floating_on_top: false
  floating_window_move_amount: "5%"
  center_new_floating_windows: true
  window_animations: false

gaps:
  inner_gap: "12"
  outer_gap: "12"

focus_borders:
  active:
    enabled: true
    color: "#0000ff"

  inactive:
    enabled: false
    color: "#ff0000"

bar:
  enabled: true
  height: "25px"
  position: "top"
  opacity: 1.5
  background: "# 20242cc4"
  foreground: "#ffffff"
  font_family: "JetBrainsMono NF"
  font_size: "13px"
  padding: "4px 6px"
  offset_x: "7"
  offset_y: "1"
  border_radius: "5"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_center:
    - type: "clock"
      time_formatting: "hh:mm tt "
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
  components_right:  
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "battery"
      label_draining: "{battery_level}%"
      label_power_saver: "{battery_level}%"
      label_charging: "{battery_level}%"

workspaces:
  - name: "1"
    display_name: "1- "
    keep_alive: false
    bind_to_monitor: 2
  - name: "2"
    display_name: "2-󰨞 "
    keep_alive: false
    bind_to_monitor: 2
  - name: "3"
    display_name: "3- "
    keep_alive: false
    bind_to_monitor: 2
  - name: "4"
    display_name: "4-󰦅 "
    keep_alive: false
    bind_to_monitor: 2
  - name: "5"
    display_name: " "
    keep_alive: false
    bind_to_monitor: 1
  - name: "social"
    display_name: " "
    keep_alive: false
    bind_to_monitor: 1

window_rules:
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  - command: "set floating"
    match_class_name: "#32770"

  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  ####################################################################
  # WORKSPACE MANAGEMENT
  ####################################################################
  - commands: ["move to workspace 1"]
    match_process_name: "/msedge|thorium/"
    match_title: "/.*/"
  - commands: ["move to workspace 2"]
    match_process_name: "/Code/"
    match_title: "/.*/"
  - commands: ["move to workspace 3"]
    match_title: "/Obsidian/"
  - commands: ["move to workspace 4"]
    match_process_name: "/zotero|WhatsApp/"
  - commands: ["move to workspace social"]
    match_process_name: "WhatsApp"
    match_title: "/^.*WhatsApp$/"
  - command: "set floating"
    match_title: "/Settings|Go to|Explorer|Flow Laucher|Todoist|Control Panel|This PC|Everything|ShareX|OBS|WhatsApp/"

binding_modes:
  - name: "resize"
    keybindings:
      - command: "resize width -2%"
        bindings: ["Left"]
      - command: "resize width +5%"
        bindings: ["Right"]
      - command: "resize height +2%"
        bindings: ["Down"]
      - command: "resize height -2%"
        bindings: ["Up"]
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

############################################################
# kEYBINDINGS
############################################################

keybindings:
  ## custom 
  # - commands: ["focus workspace 3", "exec wt"]
  #   bindings: ["Alt+X"] 
  - command: "exec wt"
    binding: "Alt+X"
  - commands: ["focus workspace 3", "exec %LOCALAPPDATA%\\Programs\\obsidian\\Obsidian.exe"]
    binding: "Alt+Shift+O" 

  ## FOCUS
  # - command: "focus left"x
  #   bindings: ["Alt+J"]
  # - command: "focus right"
  #   bindings: ["Alt+K"]
  # - command: "focus up"
  #   bindings: ["Alt+H"]
  # - command: "focus down"
  #   bindings: ["Alt+L"]

  # MOVE
  - command: "move left"
    bindings: ["Alt+Shift+A"]
  - command: "move right"
    bindings: ["Alt+Shift+S"]
  # - command: "move up"
  #   bindings: ["Alt+Shift+K"]
  # - command: "move down"
  #   bindings: ["Alt+Shift+J"]

  # RESIZE
  - command: "binding mode resize"
    binding: "Alt+R"

  - command: "tiling direction toggle"
    binding: "Alt+V"

  # - command: "focus mode toggle"
  #   binding: "Alt+Tab"

  - command: "toggle floating"
    binding: "Alt+F"

  - command: "close"
    binding: "Alt+Q"

  - command: "exit wm"
    binding: "Alt+Shift+E"

  - command: "reload config"
    binding: "Alt+Shift+R"

  # WORKSPACES
  # - command: "focus workspace default"
  #   binding: "Alt+M"
  - command: "focus workspace social"
    binding: "Alt+6"
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"