general:
  startup_commands: ["shell-exec --hide-window %userprofile%/.glzr/zebar/start.bat", "shell-exec --hide-window %userprofile%/tools/gat-gwm.exe"]

  # shutdown_commands: [""]
  

  config_reload_commands: []

  focus_follows_cursor: true

  toggle_workspace_on_refocus: false
  
  hide_method: 'cloak'
  
  show_all_in_taskbar: true
  
  cursor_jump:
    enabled: false
    trigger: "monitor_focus" # monitor_focus, window_focus

gaps:
  scale_with_dpi: true
  inner_gap: "5px"
  outer_gap:
    top: "15px"
    right: "2px"
    bottom: "1px"
    left: "2px"

window_effects:
  focused_window:
    border:
      enabled: false
      color: "#8dbc58"

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: true
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

  other_windows:
    border:
      enabled: false
      color: "#a1a1a1"
    
    hide_title_bar:
      enabled: false
    
    corner_style:
      enabled: true
      style: 'square'

window_behavior:
  initial_state: "tiling" # tiling, floating
  state_defaults:
    floating:
      centered: true
      shown_on_top: false

    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: "1"
    keep_alive: false
    bind_to_monitor: 2
  - name: "2"
    keep_alive: false
    bind_to_monitor: 2
  - name: "3"
    keep_alive: false
    bind_to_monitor: 2
  - name: "4"
    keep_alive: false
    bind_to_monitor: 2
  - name: "5"
    keep_alive: false
    bind_to_monitor: 1
  - name: "6"
    keep_alive: false
    bind_to_monitor: 1

window_rules:
  - commands: ["move --workspace 1"]
    match:
      - window_process: { regex: "msedge|brave|chrome" }
  - commands: ["move --workspace 2"]
    match:
      - window_process: { regex: "Cursor" }
  - commands: ["move --workspace 3"]
    match:
      - window_process: { regex: "Obsidian" }
  - commands: ["move --workspace 4"]
    match:
      - window_process: { regex: "zotero" }
  - commands: ["move --workspace 5"]
    match:
      - window_process: { regex: "slack" }
      - window_title: { regex: "WhatsApp" }
  - commands: ["move --workspace 6"]
    match:
      - window_process: { regex: "calibre" }
  - commands: ["set-floating"]
    match:
      - window_title:
          {
            regex: "Settings|Control Panel|Everything|ShareX",
          }
      - window_class: { regex: "CabinetWClass" }
      - window_process: { regex: "Photos|ebook-viewer" }
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "PowerToys.PowerAccent" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper*" }

      # Custom process rules
      - window_process: { regex: "Taskmgr|ScreenClippingHost" }
      - window_title: { regex: "Run" }


binding_modes:
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["right"]
      - commands: ["resize --width +2%"]
        bindings: ["left"]
      - commands: ["resize --height +2%"]
        bindings: ["down"]
      - commands: ["resize --height -2%"]
        bindings: ["up"]
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]


## GENERAL KEYBINDS

keybindings:
  - commands: ["move --direction left"]
    bindings: ["alt+shift+a"]

  - commands: ["move --direction right"]
    bindings: ["alt+shift+s"]

  - commands: ["toggle-minimized"]
    bindings: ["alt+e"]

  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+shift+w"]

  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  - commands: ["toggle-floating --centered"]
    bindings: ["alt+f"]

  - commands: ["toggle-floating"]
    bindings: ["lwin+t"]

  - commands: ["close"]
    bindings: ["alt+q"]

  - commands: ["wm-exit", "shell-exec --hide-window taskKill /IM zebar.exe"]
    bindings: ["alt+shift+e"]

  - commands: ["wm-reload-config", "shell-exec --hide-window taskKill /IM zebar.exe", "shell-exec --hide-window %userprofile%/.glzr/zebar/start.bat"]
    bindings: ["alt+shift+r"]


  ## CUSTOM KEYBINDS

  - commands: ["shell-exec wt"]
    bindings: ["alt+x"]

  - commands: ['shell-exec wt -p "Git Bash"']
    bindings: ["alt+shift+x"]

  - commands:
      [
        "focus --workspace 3",
        "shell-exec %LOCALAPPDATA%/Programs/obsidian/Obsidian.exe",
      ]
    bindings: ["alt+shift+o"]

  ## WORKSPACE MANAGEMENT

  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]

  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
